export const UiTypes = Object.freeze({
  button: 'button',
  checkboxes: 'checkboxes',
  section: 'section',
  root: 'root',
  text: 'text',
  select: 'select',
  quote: 'quote',
  money: 'money',
  date: 'date',
  toggler: 'toggler',
  radios: 'radios',
  client: 'client',
  textArea: 'textArea',
  richTextArea: 'richTextArea',
  tag: 'tag',
  email: 'email',
  link: 'link',
  integrationButton: 'integrationButton',
  moneySelect: 'moneySelect',
  currency: 'currency',
  decimal: 'decimal',
  user: 'user',
  entity: 'entity',
  policyNumber: 'policyNumber',
  number: 'number',
})
